### ISSUE TITLE
base missing in /rt-server-client/lib/Toolbox

### ISSUE THREAD

**Issue by sebibu** [rvojcik/rt-server-client#12]
Hi there,
your project seems to be a very useful addition to racktables. Unfortunately, i can't get it to work on Ubuntu 16.04 because it can't import something named "base" from the ToolBox folder:

:/opt/rt-server-client$ ./system-info.py
Traceback (most recent call last):
  File "./system-info.py", line 66, in <module>
    from ToolBox import net, dell, base
ImportError: cannot import name base

:/opt/rt-server-client/lib/ToolBox$ ll
total 20
drwxr-xr-x 4 root root 4096 Mar 15 16:28 ./
drwxr-xr-x 4 root root 4096 Mar 15 16:13 ../
drwxr-xr-x 2 root root 4096 Mar 15 16:26 dell/
-rw-r--r-- 1 root root  191 Mar 15 16:13 __init__.py
drwxr-xr-x 2 root root 4096 Mar 15 16:13 net/

any advise on that?

best,
Basti

**Comment by rvojcik** [comment]
Thank you for your report. sorry for big delay.
My mistake when I merging code from production to github.

**Comment by sebibu** [comment]
Hi rvojcik,
 many thanks for the fix, i'll test it soon! :-)

Seb
